name: flutter_thimar
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  animate_do: ^3.3.0
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.2
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.0
  google_maps_flutter: ^2.3.6
  geolocator: ^10.1.1
  kiwi: ^4.1.0
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  awesome_notifications: ^0.8.2
  carousel_slider: ^4.2.1
  pin_code_fields: ^8.0.1
  flutter_slidable: ^3.0.1
  url_launcher: ^6.2.4
  maps_launcher: ^2.2.0
  dotted_border: ^2.1.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_rating_bar: ^4.0.1
  video_player: ^2.8.2
  chewie: ^1.7.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true



  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/translation/
    - assets/lottie/






  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  fonts:
    - family:  Montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf

    - family:  ProtestRevolution
      fonts:
        - asset: assets/fonts/protestrevolution.ttf


